FROM golang AS builder
WORKDIR /app
COPY . .
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct
RUN go get && go build

FROM migrate/migrate-sqlite AS data
WORKDir /data
COPY db/migrations db/migrations
RUN migrate -database sqlite://rpic.db -path db/migrations up

FROM ubuntu
WORKDIR /usr/local/rpic
RUN apt-get update -y
COPY --from=builder /app/rpic .
COPY --from=data /data/rpic.db .
COPY www/ www/
RUN ls -la
EXPOSE 9008
CMD ["/usr/local/rpic/rpic"]
